---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: interstate-boost
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: holesky-external-secrets-store
    kind: SecretStore
  dataFrom:
    - extract:
        # Update to the correct external secret.
        # This must contain these secrets:
        # - CA_KEY: The base64 encoded CA key used by the Dirk instance.
        # - CA_CRT: The base64 encoded CA certificate used by the Dirk instance.
        # - INTERSTATE_JWT: The JWT secret used by the Interstate sidecar.
        # - CB_JWT: The Module ID and JWT secret used by the CB signer. IE. `MODULE_ID=<INTERSTATE_JWT>`. See https://commit-boost.github.io/commit-boost-client/get_started/running/binary#signer-module
        key: name:interstate-boost-secrets
        version: latest_enabled
