---
apiVersion: v1
kind: ConfigMap
metadata:
  name: interstate-boost
data:
  sidecar-env: |
    RUST_LOG=${RUST_LOG}
    RUST_BACKTRACE=${RUST_BACKTRACE}
    COMMITMENT_PORT=${COMMITMENT_PORT}
    METRICS_PORT=${METRICS_PORT}
    CHAIN=${CHAIN}
    BEACON_API_URL=${BEACON_API_URL}
    EXECUTION_API_URL=${EXECUTION_API_URL}
    ENGINE_API_URL=${ENGINE_API_URL}
    CB_URL=${CB_URL}
    BUILDER_PORT=${BUILDER_PORT}
    JWT=${JWT}
    SLOT_TIME=${SLOT_TIME}
    COMMITMENT_DEADLINE=${COMMITMENT_DEADLINE}
    FEE_RECIPIENT=${FEE_RECIPIENT}
    GATEWAY_CONTRACT=${GATEWAY_CONTRACT}
    WEB3SIGNER_URL=${WEB3SIGNER_URL}
    CA_CERT_PATH=${CA_CERT_PATH}
    CLIENT_COMBINED_PEM_PATH=${CLIENT_COMBINED_PEM_PATH}
    SIDECAR_INFO_SENDER_URL=${SIDECAR_INFO_SENDER_URL}
    COMMIT_BOOST_SIGNER_URL=${COMMIT_BOOST_SIGNER_URL}
  cb-config.toml: |
    chain = "Holesky"

    [pbs]
    host = "0.0.0.0"
    port = 18550
    genesis_time_sec=1738648239
    beacon_rpc="http://beacon:5052"

    [[relays]]
    id = "bloxroute"
    url = "https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.holesky.blxrbdn.com"

    [metrics]
    use_grafana = false
    use_cadvisor = false

    [logs]
    log_dir_path = "/var/logs/commit-boost"
    log_level = "trace"
    max_log_files = 30
  sg-config.toml: |
    chain = "Holesky"

    [pbs]
    port = 18552

    [[relays]]
    id = "bloxroute"
    url = "https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.holesky.blxrbdn.com"

    [signer]
    docker_image = "commitboost_signer"

    [signer.dirk]
    cert_path = "/etc/interstate-boost/certs/ca.crt"
    key_path = "/etc/interstate-boost/certs/ca.key"
    secrets_path = "/etc/interstate-boost/dirk_secrets"
    ca_cert_path = "/etc/interstate-boost/certs/dirk.crt"

    # Example of a single Dirk host
    [[signer.dirk.hosts]]
    url = "http://dirk:8881"
    accounts = ["Validators"]

    [signer.dirk.store]
    proxy_dir = "/etc/interstate-boost/proxy_dir"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: interstate-boost-scripts
data:
  generate_cert.sh: |
    #!/bin/bash
    set -euo pipefail
    IFS=$'\n\t'

    set -x


    generate_certs() {
    LOCATION=$1
    CA_CERT_NAME=$2
    CERT_NAME=$3

    mkdir -p "${LOCATION}"
    pushd "${LOCATION}"

    if [ ! -f "${CA_CERT_NAME}.key" ]
    then
      echo "Generating authority key"
      openssl genrsa -des3 -out "${CA_CERT_NAME}_pass.key" 4096
      openssl rsa -in "${CA_CERT_NAME}_pass.key" -out "${CA_CERT_NAME}.key"
    fi

    if [ ! -f "${CA_CERT_NAME}.crt" ]
    then
      echo "Generating authority crt"
      openssl req -x509 -new -nodes -key "${CA_CERT_NAME}.key" -sha256 -days 1825 -out "${CA_CERT_NAME}.crt"
    fi

    cat >"${CERT_NAME}.ext" <<EOEXT
    authorityKeyIdentifier=keyid,issuer
    basicConstraints=CA:FALSE
    keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
    subjectAltName = @alt_names

    [alt_names]
    DNS.1 = "${CERT_NAME}"
    EOEXT

    openssl genrsa -out "${CERT_NAME}.key" 4096
    openssl req -out "${CERT_NAME}.csr" -key "${CERT_NAME}.key" -new -subj "/CN=${CERT_NAME}" -addext "subjectAltName=DNS:${CERT_NAME}"
    openssl x509 -req -in "${CERT_NAME}.csr" -CA "${CA_CERT_NAME}.crt" -CAkey "${CA_CERT_NAME}.key" -CAcreateserial -out "${CERT_NAME}.crt" -days 1825 -sha256 -extfile "${CERT_NAME}.ext"

    cat "${CA_CERT_NAME}.crt" "${CA_CERT_NAME}.key" > "${CA_CERT_NAME}.pem"

    popd
    }

    generate_certs "$@"
