---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: holesky

helmCharts:
  - name: generic-app
    repo: https://nethermindeth.github.io/helm-charts
    version: 1.1.2
    valuesFile: values.yaml
    releaseName: interstate-boost-holesky
    namespace: holesky

resources:
  - configmap.yaml
  - external-secret.yaml
  - servicemonitor.yaml

# Patch the service to add extraContainers ports.
patches:
  - path: service.yaml
    target:
      kind: Service
      name: interstate-boost-holesky
