---
apiVersion: v1
kind: Service
metadata:
  name: interstate-boost-holesky
spec:
  ports:
    - name: http
      port: 18550
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 9091
      protocol: TCP
      targetPort: metrics
    - name: signer
      port: 18551
      protocol: TCP
      targetPort: signer
    - name: sg-metrics
      port: 9092
      protocol: TCP
      targetPort: sg-metrics
    - name: commitments
      port: 9063
      protocol: TCP
      targetPort: commitments
    - name: builder
      port: 9064
      protocol: TCP
      targetPort: builder
    - name: sc-metrics
      port: 8018
      protocol: TCP
      targetPort: sc-metrics
