{{- if .Values.cb.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-cb
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/component: cb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- if .Values.cb.deployment.annotations }}
  annotations:
    {{- toYaml .Values.cb.deployment.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.cb.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
      app.kubernetes.io/component: cb
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.cb.deployment.updateStrategy.type | default "RollingUpdate" }}
    {{- if eq (.Values.cb.deployment.updateStrategy.type | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.cb.deployment.updateStrategy.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.cb.deployment.updateStrategy.maxUnavailable | default 0 }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName }}
        app.kubernetes.io/component: cb
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.cb.deployment.podLabels }}
        {{- toYaml .Values.cb.deployment.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.cb.deployment.podAnnotations }}
        {{- toYaml .Values.cb.deployment.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.cb.deployment.affinity }}
      affinity:
        {{- toYaml .Values.cb.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.cb.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.cb.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.cb.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.cb.deployment.tolerations | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.cb.deployment.terminationGracePeriodSeconds | default 30 }}
      securityContext:
        {{- toYaml .Values.cb.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: interstate-cb
          image: "{{ .Values.cb.image.repository }}:{{ .Values.cb.image.tag }}"
          imagePullPolicy: {{ .Values.cb.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            {{- toYaml .Values.cb.deployment.containerSecurityContext | nindent 12 }}
          env:
            - name: CB_CONFIG
              value: "/app/config/cb-config.toml"
            - name: METRICS_SERVER
              value: "10000"
            - name: RUST_LOG
              value: {{ .Values.cb.deployment.logLevel | default "debug" | quote }}
            {{- if .Values.cb.deployment.extraEnv }}
            {{- toYaml .Values.cb.deployment.extraEnv | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.appName }}-cb-config
          ports:
            - name: http
              containerPort: {{ .Values.cb.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: commitment
              containerPort: 9063
              protocol: TCP
          resources:
            {{- toYaml .Values.cb.deployment.resources | nindent 12 }}
          {{- if .Values.cb.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.cb.deployment.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.cb.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.cb.deployment.readinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.appName }}-cb-config
            items:
              - key: cb-config.toml
                path: cb-config.toml
{{- end }}
