---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-sidecar-config
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/component: sidecar
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- if .Values.sidecar.annotations }}
  annotations:
    {{- toYaml .Values.sidecar.annotations | nindent 4 }}
  {{- end }}
data:
  .env: |
    RUST_LOG={{ .Values.sidecar.env.rustLog | default "debug" }}
    RUST_BACKTRACE={{ .Values.sidecar.env.rustBacktrace | default "1" }}
    CARGO_MANIFEST_DIR={{ .Values.sidecar.env.cargoManifestDir | default "/app" }}
    COMMITMENT_PORT={{ .Values.sidecar.env.commitmentPort | default "9063" }}
    METRICS_PORT={{ .Values.sidecar.env.metricsPort | default "8018" }}
    CHAIN={{ .Values.sidecar.env.chain | default "kurtosis" }}
    VALIDATOR_INDEXES={{ .Values.sidecar.env.validatorIndexes | default "0..64" }}
    BEACON_API_URL={{ .Values.sidecar.env.beaconApiUrl }}
    EXECUTION_API_URL={{ .Values.sidecar.env.executionApiUrl }}
    ENGINE_API_URL={{ .Values.sidecar.env.engineApiUrl }}
    COLLECTOR_URL={{ .Values.sidecar.env.collectorUrl }}
    COLLECTOR_SOCKET={{ .Values.sidecar.env.collectorSocket }}
    BUILDER_PORT={{ .Values.sidecar.env.builderPort | default "9064" }}
    JWT={{ .Values.sidecar.env.jwt }}
    SLOT_TIME={{ .Values.sidecar.env.slotTime | default "2" }}
    COMMITMENT_DEADLINE={{ .Values.sidecar.env.commitmentDeadline | default "100" }}
    FEE_RECIPIENT={{ .Values.sidecar.env.feeRecipient }}
    DELEGATIONS_PATH={{ .Values.sidecar.env.delegationsPath | default "./delegations/delegations.json" }}
    GATEWAY_CONTRACT={{ .Values.sidecar.env.gatewayContract }}
    WEB3SIGNER_URL={{ .Values.sidecar.env.web3SignerUrl }}
    CA_CERT_PATH={{ .Values.sidecar.env.caCertPath }}
    CLIENT_COMBINED_PEM_PATH={{ .Values.sidecar.env.clientCombinedPemPath }}
    SIDECAR_INFO_SENDER_URL={{ .Values.sidecar.env.sidecarInfoSenderUrl }}
    COMMIT_BOOST_SIGNER_URL={{ .Values.sidecar.env.commitBoostSignerUrl }}
    {{- if .Values.sidecar.deployment.extraEnv }}
    {{- range .Values.sidecar.deployment.extraEnv }}
    {{ .name }}={{ .value }}
    {{- end }}
    {{- end }}

