{{- if .Values.cb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-cb
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/component: cb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- if .Values.cb.annotations }}
  annotations:
    {{- toYaml .Values.cb.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/component: cb
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.cb.port }}
      targetPort: {{ .Values.cb.port }}
      protocol: TCP
{{- end }}
