name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run unit tests
      run: cargo test
    

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Clippy
      run: rustup component add clippy
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run Clippy
      run: cargo clippy -- -D warnings
